source 'https://github.com/CocoaPods/Specs.git'
source 'git@git.coding.net:JJjianjian/QNBJPodSpec.git'

use_frameworks!

target 'QNBaseComponent_Example' do
    
#    本地私有库
    pod 'QNBaseComponent', :path => '../'
    
#    远程私有库
#  pod 'QNBaseComponent/QNBasicConfiguration'
#  pod 'QNBaseComponent/QNCategory'
#  pod 'QNBaseComponent/QNTool'


  target 'QNBaseComponent_Tests' do
    inherit! :search_paths

  end
end
